export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const ERROR_FETCH_CATEGORIES = 'ERROR_FETCH_CATEGORIES';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const AUTH_ACTION_SUCCESS = 'AUTH_ACTION_SUCCESS';
export const API_ACTION_ERROR = 'API_ACTION_ERROR';
export const CLEAR_API_ACTION_ERROR = 'CLEAR_API_ACTION_ERROR';
export const CLEAR_AUTH_USER_DATA = 'CLEAR_AUTH_USER_DATA';
